### ISSUE TITLE
Add functionality to export in wiggle format

### ISSUE THREAD

**Issue by mfiers** [mfiers/hagfish#3]
Export hagfish plots in WIG format - for visualization in other tools, such as IGV.

wiggle: http://genome.ucsc.edu/goldenPath/help/wiggle.html

(as requested by @alpapan)

**Comment by mfiers** [comment]
There is a hagfish_wiggle script now

run as:

```
hagfish_wiggle
```

or:

```
hagfish_wiggle contig_name
```

cheers
Mark

(@alpapan @RCrowhurst)

**Comment by alpapan** [comment]
parsing the -s option is not working (but without -s is fine as you set seqIds = args)...

**Comment by alpapan** [comment]
regardless of the value of bin...

HAGFISH INFO   reading seqInfo/4_vs_contigs_sopra.fasta.sam.fix.seqinfo to get seqinfo
HAGFISH INFO   discovered 9339 sequences
HAGFISH INFO   Processing csiro20_scaffold_20
HAGFISH INFO   Outputting csiro20_scaffold_20
HAGFISH DEBUG  loading combined/csiro20_scaffold_20 r_ok
HAGFISH DEBUG  loading combined/csiro20_scaffold_20 r_low
HAGFISH DEBUG  loading combined/csiro20_scaffold_20 r_high
HAGFISH DEBUG  loading combined/csiro20_scaffold_20 r_ok_ends
HAGFISH DEBUG  loading combined/csiro20_scaffold_20 r_low_ends
HAGFISH DEBUG  loading combined/csiro20_scaffold_20 r_high_ends
HAGFISH INFO   read 2282112 datapoints
HAGFISH INFO   sequence length of csiro20_scaffold_20 is 2282112
/sw/python/2.7.2-1/lib/python2.7/site-packages/numpy/lib/function_base.py:489: RuntimeWarning: invalid value encountered in double_scalars

**Comment by alpapan** [comment]
and with python 3.2...
Traceback (most recent call last):
  File "/home/pap056/software/hagfish/hagfish_wiggle", line 7, in <module>
    import numpy as np
  File "/sw/python/3.2/lib/python3.2/site-packages/numpy/**init**.py", line 136, in <module>
    from . import add_newdocs
  File "/sw/python/3.2/lib/python3.2/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from numpy.lib import add_newdoc
  File "/sw/python/3.2/lib/python3.2/site-packages/numpy/lib/**init**.py", line 13, in <module>
    from .polynomial import *
  File "/sw/python/3.2/lib/python3.2/site-packages/numpy/lib/polynomial.py", line 17, in <module>
    from numpy.linalg import eigvals, lstsq
  File "/sw/python/3.2/lib/python3.2/site-packages/numpy/linalg/**init**.py", line 48, in <module>
    from .linalg import *
  File "/sw/python/3.2/lib/python3.2/site-packages/numpy/linalg/linalg.py", line 23, in <module>
    from numpy.linalg import lapack_lite
ImportError: /sw/python/3.2/lib/python3.2/site-packages/numpy/linalg/lapack_lite.cpython-32m.so: undefined symbol: zgesdd_

but it works with python 2.6.5 or 2.7.1 !
